% Notes on HeroX project
%
% \today

```{r, echo=FALSE}
# Load data from Maureen
read.csv("../Data/iContact/CompareMessage_maureen1.csv") -> dat1
read.csv("../Data/iContact/CompareMessage_maureen2.csv") -> dat2
read.csv("../Data/iContact/CompareMessage_maureen3.csv") -> dat3
rbind(dat1, dat2, dat3) -> dat
dat$sender <- "Maureen"

# From Liz
read.csv("../Data/iContact/CompareMessage_liz.csv") -> dat1
dat1$sender <- "Liz"
rbind(dat1, dat) -> dat

# From Kyla
read.csv("../Data/iContact/CompareMessage_kyla.csv") -> dat1
dat1$sender <- "Kyla"
rbind(dat1, dat) -> dat

# From Nidhi 
read.csv("../Data/iContact/CompareMessage_nidhi.csv") -> dat1
dat1$sender <- "Nidhi"
rbind(dat1, dat) -> dat
```

```{r, message=FALSE, echo=FALSE, fig.width=9, fig.cap="Contacts sent to, emails opened, clicks."}
attach(dat)

contacts_qtl <- cut(Contacts_Sent_To, quantile(Contacts_Sent_To), include=T)

# Dates
x <- as.Date(Date, fo="%B %d, %Y")
x[is.na(x)] <- as.Date(Date[is.na(x)])
date <- x

# Statistics
par(mfrow=c(1, 3))
hist(Contacts_Sent_To, "Scott")
plot(date, Opened, cex=Contacts_Sent_To/1e4)
ols <- lm(Opened ~ 1, weights=Contacts_Sent_To)
mtext(sprintf("Mean=%0.2f%s", coef(ols),"%"), 3)
plot(date, Clicks, cex=Contacts_Sent_To/1e4)
ols <- lm(Clicks ~ 1, weights=Contacts_Sent_To)
mtext(sprintf("Mean=%0.2f%s", coef(ols), "%"), 3)
```

\newpage

```{r, echo=FALSE, fig.cap="Days of the week", fig.width=9}
# By the day of the week
days.of.week <- weekdays(x=as.Date(seq(7), origin="1950-01-01"))
wdays <- factor(weekdays(date), levels=days.of.week)
par(mfrow=c(1, 2))
boxplot(Opened ~ wdays, ylab="Opened")
boxplot(Clicks ~ wdays, ylab="Clicks")
```

\newpage


```{r, echo=FALSE}
fit.open <- lm(Opened ~ wdays + sender + contacts_qtl, weights=Contacts_Sent_To)
fit.clicks <- lm(Clicks ~ wdays + sender + contacts_qtl, weights=Contacts_Sent_To)
summary(fit.open)
summary(fit.clicks)
```

\newpage

```{r, echo=FALSE, message=FALSE, fig.width=9, fig.cap="Relationship between competitors and unique visits."}
read.csv("../Data/HeroX Challenge Data_Daily_10Aug16.csv") -> dat
# head(dat)
# 
# # 20 challenges
# table(dat$challenge)
# table(dat$challenge.type)
competitors <- tapply(dat$rolling.comp, dat$challenge, tail, n=1) 
submissions <- tapply(dat$rolling.sub, dat$challenge, tail, n=1) 
unique.views <- tapply(dat$unique.views, dat$challenge, tail, n=1) 
prizes <- tapply(dat$prize, dat$challenge, tail, n=1) 

# # Views and competitors
plot(log(unique.views), log(competitors), bty='n', xaxt="n",yaxt='n')
text(log(unique.views), log(competitors), names(competitors), pos=sample(4, length(competitors), replace=TRUE), xpd=TRUE, col=2)
axis(1, at=log(unique.views), unique.views)
axis(2, at=log(competitors), competitors)
abline(ols <- lm(log(competitors) ~ log(unique.views), subset=competitors>0))
lab <- sprintf("E[comp] = exp(%0.2f + %0.2f * log(views))", coef(ols)[1], coef(ols)[2])
mtext(lab, 3)
```


```{r, echo=FALSE, message=FALSE, fig.width=9, fig.cap="Relationship between prize pool and unique visits."}
# Prizes and views
plot(log(prizes), log(unique.views), bty='n', xaxt="n", yaxt="n")
text(log(prizes), log(unique.views), names(unique.views), pos=sample(4, length(unique.views), replace=TRUE), xpd=TRUE, col=2)
axis(1, at=log(prizes), prizes)
axis(2, at=log(unique.views), unique.views)
abline(ols <- lm(log(unique.views) ~ log(prizes), subset=competitors>0), lwd=2)
lab <- sprintf("E[views] = exp(%0.2f + %0.2f * log(prize))", coef(ols)[1], coef(ols)[2])
legend("top", lty=1, lab, bty="n")
```
